### ISSUE TITLE
Double chests seem to break hoppers

### ISSUE THREAD

**Issue by crimsonblod** [CivClassic/Citadel#25] opened 2020-05-15 03:16 UTC
Hoppers do not seem to be able to push or pull from reinforced double chests.
![Here](https://user-images.githubusercontent.com/28963633/82007408-c3c02400-962f-11ea-8f43-8a11e8859e45.png) we can see that the double chests cannot be pushed or pulled from when reinforced, regardless of whether they are single or double reinforced. But testing shows that unreinforced doublechests can be pulled from or pushed into.

I'm not sure if this is the only instance of hoppers breaking, but it seems to be the primary issue that was afflicting our designs so far. Removing all double chests fix the design we had that was breaking hoppers so frequently.

**Comment by Maxopoly** [comment] 2020-05-15 09:33
Possibly caused by https://github.com/CivClassic/Citadel/issues/26

**Comment by Maxopoly** [comment] 2020-05-22 14:54
Possibly fixed by https://github.com/CivClassic/Citadel/pull/27. Will need testing after the next restart

**Comment by Maxopoly** [comment] 2020-05-25 05:57
@crimsonblod Any updates regarding whether this is fixed?

**Comment by crimsonblod** [comment] 2020-05-25 13:47
Singlechests are still the only ones that work with hoppers, pushing or pulling.  Sorry for the delay. Even with newly placed chests and hoppers.

**Comment by Protonull** [comment] 2020-07-06 11:20
After doing some investigation, the reason why this is occurring is because double chests have a distinct and incompatible block data type to other block storage types. And so when `Container` is checked for [here](https://github.com/CivClassic/Citadel/blob/master/src/main/java/vg/civcraft/mc/citadel/listener/InventoryListener.java#L21), double chests are excluded and thus are treated by `InventoryMoveItemEvent` as being un-reinforced / insecure.

**Comment by Maxopoly** [comment] 2020-07-06 11:35
Ah that must have changed then, Container used to include anything holding an inventory, but alright. Good tracking down.

**Closed as completed** 2020-07-09 00:56 UTC
Labels: bug, more information needed
